### ISSUE TITLE
Refactor most of the code

### ISSUE THREAD

**Issue by galaktahs** [Mytikas-LTU/ELPIS-ONE#15]
Refactor most of the code to improve readability and stability

- [x] Create Accelerometer class
- [x] Extract Vec3 and Quat to structs and add some member functions
- [x] create barometer class
- [x] create cardwriter class

**Comment by isakensak** [comment]
We should refactor the components to classes, for example an accelerometer class with functions init() and read(). This will reduce the size of loop() and setup(), as well as make the main file more readable.

**Comment by isakensak** [comment]
- [ ] Create Accelerometer class
- [ ] create barometer class
- [ ] create cardwriter class
